### ISSUE TITLE
5.16.90 compatibility?

### ISSUE THREAD

**Issue by Vistaus** [tildearrow/kwin-lowlatency#47]
I like to live on the edge and so I use Plasma 5.16.90, but the only thing I can't use still is kwin-5.16.90 because your patch fails on the kwin-5.16.90 source code. Are you planning to make it compatible soon? :D

**Comment by tildearrow** [comment]
5.17 will be a re-write since most of the code breaks in that version. And I don't have time right now. Sorry...

**Comment by Vistaus** [comment]
No problem, mate! I understand. Hope you'll have time again at some point though 'cause I can't imagine Plasma life without kwin-lowlatency :smiley_cat:

**Comment by tildearrow** [comment]
```
/projects/kwin/screenlockerwatcher.cpp: In member function ‘void KWin::ScreenLockerWatcher::serviceOwnerChanged(const QString&, const QString&, const QString&)’:
/projects/kwin/screenlockerwatcher.cpp:84:62: error: ‘AboutToLock’ is not a member of ‘OrgKdeScreensaverInterface’
   84 |         connect(m_kdeInterface, &OrgKdeScreensaverInterface::AboutToLock, this, &ScreenLockerWatcher::aboutToLock);
      |                                                              ^~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin.dir/build.make:1109: CMakeFiles/kwin.dir/screenlockerwatcher.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: CMakeFiles/kwin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by Izaic** [comment]
Agreed! I can't use plasma without kwin-lowlatency or wayland anymore. And wayland is just too buggy. Maybe roman's patches will solve things, but they seem to be a ways off.

**Comment by tildearrow** [comment]
I'm so sorry but 5.16.90 will not be possible as the 5.17 tars are already out...
5.17.0 will be available though as soon as they release it.

**Comment by ShayBox** [comment]
Ah I couldn't figure out why my desktop was so broken when trying kde-unstable, I remembered I was using this today :smile:

**Comment by KAMiKAZOW** [comment]
The kwin-lowlatency 5.16.5 binary I published in my OBS repo works just fine with Plasma 5.17beta.

**Comment by Vistaus** [comment]
@KAMiKAZOW Yes, it does. But that's NOT the issue here: the issue is that kwin-lowlatency currently doesn't work with **KWIN** 5.17

**Comment by KAMiKAZOW** [comment]
https://github.com/tildearrow/kwin-lowlatency/commit/07a98993b3fb643a912aeb8aa78aa357691884be 🤷

**Comment by Vistaus** [comment]
> [07a9899](https://github.com/tildearrow/kwin-lowlatency/commit/07a98993b3fb643a912aeb8aa78aa357691884be) 🤷

The port to KWin 5.17 is still a WIP.

**Comment by tildearrow** [comment]
Work in progr-

**Comment by tildearrow** [comment]
Finally!

**Comment by Vistaus** [comment]
Woohoo! Who da man? You da man!

![yellow-octopus-party-hard-meme-8](https://user-images.githubusercontent.com/1716229/67126874-662e3b00-f1f8-11e9-9f7f-c9607f2e4fcf.jpg)

**Comment by KAMiKAZOW** [comment]
Currently updating the openSUSE package. Hopefully dependencies or so didn't change much.

**Comment by robinlahtinen** [comment]
Ubuntu PPA forever forgotten

**Comment by KAMiKAZOW** [comment]
> Ubuntu PPA forever forgotten

Create one yourself. I did for openSUSE. Wasn't that hard.

**Comment by tildearrow** [comment]
> Ubuntu PPA forever forgotten

PPA/Debian packaging concept is too difficult for me to understand and get working right...
