### ISSUE TITLE
Unable to compile on Manjaro (with KDE 5.19)

### ISSUE THREAD

**Issue by RTheren** [tildearrow/kwin-lowlatency#94]
Hi all,

After today's update, I am unable to compile kwin-lowlatency either via AUR package, or through git clone.

**This is the output of manual build:**
[ 47%] Built target kwin_cubeslide_config
[ 47%] Building CXX object effects/CMakeFiles/kwin4_effect_builtins.dir/blur/blur.cpp.o
[ 47%] Building CXX object effects/CMakeFiles/kwin4_effect_builtins.dir/snaphelper/snaphelper.cpp.o
[ 47%] Building CXX object effects/CMakeFiles/kwin4_effect_builtins.dir/startupfeedback/startupfeedback.cpp.o
/ssd/Git/kwin-lowlatency/effects/blur/blur.cpp: In constructor ‘KWin::BlurEffect::BlurEffect()’:
/ssd/Git/kwin-lowlatency/effects/blur/blur.cpp:61:28: error: ‘class KWaylandServer::BlurManagerInterface’ has no member named ‘create’
   61 |             m_blurManager->create();
      |                            ^~~~~~
/ssd/Git/kwin-lowlatency/platformsupport/scenes/opengl/abstract_egl_backend.cpp: In member function ‘virtual void KWin::AbstractEglTexture::updateTexture(KWin::WindowPixmap*)’:
/ssd/Git/kwin-lowlatency/platformsupport/scenes/opengl/abstract_egl_backend.cpp:426:30: error: ‘class KWaylandServer::SurfaceInterface’ has no member named ‘scale’
  426 |     createTextureSubImage(s->scale(), image, damage);
      |                              ^~~~~
make[2]: *** [effects/CMakeFiles/kwin4_effect_builtins.dir/build.make:364: effects/CMakeFiles/kwin4_effect_builtins.dir/blur/blur.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/build.make:96: platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/abstract_egl_backend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6576: platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:4817: effects/CMakeFiles/kwin4_effect_builtins.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**And this is AUR version:**
[ 45%] Built target kwin_mousemark_config
[ 45%] Built target kwin_glide_config
/tmp/makepkg/kwin-lowlatency/src/kwin-lowlatency/platformsupport/scenes/opengl/abstract_egl_backend.cpp: In member function ‘virtual void KWin::AbstractEglTexture::updateTexture(KWin::WindowPixmap*)’:
/tmp/makepkg/kwin-lowlatency/src/kwin-lowlatency/platformsupport/scenes/opengl/abstract_egl_backend.cpp:426:30: error: ‘class KWaylandServer::SurfaceInterface’ has no member named ‘scale’
  426 |     createTextureSubImage(s->scale(), image, damage);
      |                              ^~~~~
make[2]: *** [platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/build.make:96: platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/abstract_egl_backend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6576: platformsupport/scenes/opengl/CMakeFiles/SceneOpenGLBackend.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Built target kcm_kwinrules
[ 45%] Built target kwineffects
[ 45%] Built target kwin_rules_dialog
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x55dc5930e830)

Looking forward to any answer.

**Comment by tildearrow** [comment]
Oooo Manjaro updated to 5.19!

**Comment by RTheren** [comment]
Indeed. Updated today, couldn't boot to desktop (probably kwin), changed packages to plasma-git, and I am in. Seeing normal kwin to stutter when moving through desktops is a pain for my eyes.

**Comment by tildearrow** [comment]
Hmmm... Are you still using plasma-git? If so, then switch back to normal Plasma 5.19 (vanilla KWin included), clean the build directory and try again.

**Comment by RTheren** [comment]
Damn. That fixed it.

No idea how or why, but I am so damn happy :)

**Comment by tildearrow** [comment]
Amazing to hear! :o

Thank you for the heads up though :>
